SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tenants](
	[TenantUID] [uniqueidentifier] NOT NULL,
	[Deleted] [bit] NOT NULL
PRIMARY KEY CLUSTERED 
(
	[TenantUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Chats](
	[ChatID] [int] IDENTITY(1,1) NOT NULL,
	[ChatUID] [uniqueidentifier] ROWGUIDCOL NOT NULL,
	[TenantUID] [uniqueidentifier] NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[Deleted] [bit] NOT NULL
PRIMARY KEY CLUSTERED 
(
	[ChatID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Chats]  WITH CHECK ADD FOREIGN KEY([TenantUID])
REFERENCES [dbo].[Tenants] ([TenantUID])
GO

CREATE NONCLUSTERED INDEX [IX_Chats_TenantUID] ON [dbo].[Chats]
(
	[TenantUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_Unique_ChatUID] ON [dbo].[Chats]
(
	[ChatUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Chats] ADD  CONSTRAINT [DF_Chats_ChatUID]  DEFAULT (newid()) FOR [ChatUID]
GO

CREATE SCHEMA [Security]
GO

CREATE FUNCTION [Security].[SecurityPredicate](@TenantUID UNIQUEIDENTIFIER)
    RETURNS TABLE
    WITH SCHEMABINDING
AS
    RETURN
        SELECT 1 AS Result
    WHERE CAST(SESSION_CONTEXT(N'TenantUID') AS UNIQUEIDENTIFIER) = @TenantUID
GO

CREATE SECURITY POLICY [Security].[ChatsPolicy]
    ADD FILTER PREDICATE [Security].[SecurityPredicate]([TenantUID]) 
        ON [dbo].[Chats],
    ADD BLOCK PREDICATE [Security].[SecurityPredicate]([TenantUID]) 
        ON [dbo].[Chats] AFTER INSERT,
    ADD BLOCK PREDICATE [Security].[SecurityPredicate]([TenantUID]) 
        ON [dbo].[Chats] AFTER UPDATE,
    ADD BLOCK PREDICATE [Security].[SecurityPredicate]([TenantUID]) 
        ON [dbo].[Chats] BEFORE DELETE,
    ADD BLOCK PREDICATE [Security].[SecurityPredicate]([TenantUID]) 
        ON [dbo].[Chats] BEFORE UPDATE
WITH (STATE = ON, SCHEMABINDING = ON)
GO