//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emailservice.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmailResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("emailservice.Resources.EmailResources", typeof(EmailResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;box-sizing:border-box;display:block;max-width:600px;margin:0 auto;padding:10px&quot;&gt;&lt;span style=&quot;color:transparent;display:none;height:0;max-height:0;max-width:0;opacity:0;overflow:hidden;width:0&quot;&gt;Let&apos;s confirm your email address.&lt;/span&gt;
        ///			&lt;div style=&quot;box-sizing:border-box;width:100%;margin-bottom:30px;margin-top:15px&quot;&gt;
        ///			&lt;table style=&quot;box-sizing:border-box;width:100%;border-spacing:0;border-collapse:separate!important&quot; width=&quot;100%&quot;&gt;
        ///				&lt;tbody&gt;
        ///					&lt;tr&gt;
        ///						&lt;td align=&quot;left&quot; style=&quot;box-siz [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VerificationBody {
            get {
                return ResourceManager.GetString("VerificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to DailyScrum! Confirm Your Email.
        /// </summary>
        internal static string VerificationSubject {
            get {
                return ResourceManager.GetString("VerificationSubject", resourceCulture);
            }
        }
    }
}
